*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:38:12 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x1a0a500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a0a500 pid: 20960 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20960)
spawned uWSGI worker 1 (pid: 20962, cores: 8)
spawned uWSGI worker 2 (pid: 20963, cores: 8)
spawned uWSGI worker 3 (pid: 20964, cores: 8)
spawned uWSGI worker 4 (pid: 20965, cores: 8)
spawned uWSGI worker 5 (pid: 20966, cores: 8)
spawned uWSGI worker 6 (pid: 20967, cores: 8)
spawned uWSGI worker 7 (pid: 20968, cores: 8)
spawned uWSGI worker 8 (pid: 20990, cores: 8)
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:40:39 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x194a500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x194a500 pid: 21062 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21062)
spawned uWSGI worker 1 (pid: 21064, cores: 8)
spawned uWSGI worker 2 (pid: 21065, cores: 8)
spawned uWSGI worker 3 (pid: 21066, cores: 8)
spawned uWSGI worker 4 (pid: 21067, cores: 8)
spawned uWSGI worker 5 (pid: 21068, cores: 8)
spawned uWSGI worker 6 (pid: 21069, cores: 8)
spawned uWSGI worker 7 (pid: 21070, cores: 8)
spawned uWSGI worker 8 (pid: 21071, cores: 8)
[2018-12-17 20:49:34,984] ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/items-rest/app.py", line 36, in create_tables
    db.create_all()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 887, in get_engine
    state = get_state(app)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_state
    'The sqlalchemy extension was not registered to the current ' \
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
[pid: 21064|app: 0|req: 1/1] 81.171.98.46 () {44 vars in 603 bytes} [Mon Dec 17 20:49:34 2018] POST /auth => generated 291 bytes in 10 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 1)
announcing my loyalty to the Emperor...
Mon Dec 17 20:50:34 2018 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:50:39 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x1817500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1817500 pid: 21430 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21430)
spawned uWSGI worker 1 (pid: 21432, cores: 8)
spawned uWSGI worker 2 (pid: 21433, cores: 8)
spawned uWSGI worker 3 (pid: 21434, cores: 8)
spawned uWSGI worker 4 (pid: 21435, cores: 8)
spawned uWSGI worker 5 (pid: 21436, cores: 8)
spawned uWSGI worker 6 (pid: 21437, cores: 8)
spawned uWSGI worker 7 (pid: 21438, cores: 8)
spawned uWSGI worker 8 (pid: 21439, cores: 8)
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:52:39 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0xdd8500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xdd8500 pid: 21574 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21574)
spawned uWSGI worker 1 (pid: 21576, cores: 8)
spawned uWSGI worker 2 (pid: 21577, cores: 8)
spawned uWSGI worker 3 (pid: 21578, cores: 8)
spawned uWSGI worker 4 (pid: 21579, cores: 8)
spawned uWSGI worker 5 (pid: 21580, cores: 8)
spawned uWSGI worker 6 (pid: 21581, cores: 8)
spawned uWSGI worker 7 (pid: 21582, cores: 8)
spawned uWSGI worker 8 (pid: 21583, cores: 8)
[2018-12-17 20:53:02,721] ERROR in app: Exception on /auth [POST]
Traceback (most recent call last):
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/items-rest/app.py", line 36, in create_tables
    db.create_all()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 887, in get_engine
    state = get_state(app)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_state
    'The sqlalchemy extension was not registered to the current ' \
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
[pid: 21579|app: 0|req: 1/1] 81.171.98.46 () {44 vars in 603 bytes} [Mon Dec 17 20:53:02 2018] POST /auth => generated 291 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
Mon Dec 17 20:56:47 2018 - received message 1 from emperor
...gracefully killing workers...
Gracefully killing worker 1 (pid: 21576)...
Gracefully killing worker 2 (pid: 21577)...
Gracefully killing worker 3 (pid: 21578)...
Gracefully killing worker 4 (pid: 21579)...
Gracefully killing worker 5 (pid: 21580)...
Gracefully killing worker 6 (pid: 21581)...
Gracefully killing worker 7 (pid: 21582)...
Gracefully killing worker 8 (pid: 21583)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/items-rest/socket.sock)
running /var/www/html/items-rest/env/bin/uwsgi
*** has_emperor mode detected (fd: 6) ***
[uWSGI] getting INI configuration from /var/www/html/items-rest/uwsgi.ini
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:56:48 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x2051440
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
Traceback (most recent call last):
  File "/var/www/html/items-rest/run.py", line 8, in <module>
    db.init_app(app)
AttributeError: module 'db' has no attribute 'init_app'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 21574)
spawned uWSGI worker 1 (pid: 21741, cores: 8)
spawned uWSGI worker 2 (pid: 21742, cores: 8)
spawned uWSGI worker 3 (pid: 21743, cores: 8)
spawned uWSGI worker 4 (pid: 21744, cores: 8)
spawned uWSGI worker 5 (pid: 21745, cores: 8)
spawned uWSGI worker 6 (pid: 21746, cores: 8)
spawned uWSGI worker 7 (pid: 21754, cores: 8)
spawned uWSGI worker 8 (pid: 21755, cores: 8)
Mon Dec 17 20:57:08 2018 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 20:57:13 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x22f6500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
Traceback (most recent call last):
  File "/var/www/html/items-rest/run.py", line 8, in <module>
    db.init_app(app)
AttributeError: module 'db' has no attribute 'init_app'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21820)
spawned uWSGI worker 1 (pid: 21822, cores: 8)
spawned uWSGI worker 2 (pid: 21823, cores: 8)
spawned uWSGI worker 3 (pid: 21824, cores: 8)
spawned uWSGI worker 4 (pid: 21825, cores: 8)
spawned uWSGI worker 5 (pid: 21826, cores: 8)
spawned uWSGI worker 6 (pid: 21827, cores: 8)
spawned uWSGI worker 7 (pid: 21828, cores: 8)
spawned uWSGI worker 8 (pid: 21829, cores: 8)
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 21:00:30 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x11cf500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
Traceback (most recent call last):
  File "/var/www/html/items-rest/run.py", line 8, in <module>
    db.init_app(app)
AttributeError: module 'db' has no attribute 'init_app'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21918)
spawned uWSGI worker 1 (pid: 21920, cores: 8)
spawned uWSGI worker 2 (pid: 21921, cores: 8)
spawned uWSGI worker 3 (pid: 21922, cores: 8)
spawned uWSGI worker 4 (pid: 21923, cores: 8)
spawned uWSGI worker 5 (pid: 21924, cores: 8)
spawned uWSGI worker 6 (pid: 21925, cores: 8)
spawned uWSGI worker 7 (pid: 21926, cores: 8)
spawned uWSGI worker 8 (pid: 21927, cores: 8)
--- no python application found, check your startup logs for errors ---
[pid: 21922|app: -1|req: -1/1] 81.171.98.46 () {44 vars in 603 bytes} [Mon Dec 17 21:00:58 2018] POST /auth => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
--- no python application found, check your startup logs for errors ---
[pid: 21925|app: -1|req: -1/2] 81.171.98.46 () {44 vars in 603 bytes} [Mon Dec 17 21:02:46 2018] POST /auth => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
announcing my loyalty to the Emperor...
--- no python application found, check your startup logs for errors ---
[pid: 21925|app: -1|req: -1/3] 81.171.98.46 () {44 vars in 611 bytes} [Mon Dec 17 21:02:55 2018] POST /register => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
Mon Dec 17 21:08:34 2018 - received message 1 from emperor
...gracefully killing workers...
Gracefully killing worker 1 (pid: 21920)...
Gracefully killing worker 2 (pid: 21921)...
Gracefully killing worker 3 (pid: 21922)...
Gracefully killing worker 4 (pid: 21923)...
Gracefully killing worker 5 (pid: 21924)...
Gracefully killing worker 6 (pid: 21925)...
Gracefully killing worker 7 (pid: 21926)...
Gracefully killing worker 8 (pid: 21927)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
binary reloading uWSGI...
chdir() to /
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/var/www/html/items-rest/socket.sock)
running /var/www/html/items-rest/env/bin/uwsgi
*** has_emperor mode detected (fd: 6) ***
[uWSGI] getting INI configuration from /var/www/html/items-rest/uwsgi.ini
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 21:08:35 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x2591440
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2591440 pid: 21918 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 21918)
spawned uWSGI worker 1 (pid: 22105, cores: 8)
spawned uWSGI worker 2 (pid: 22106, cores: 8)
spawned uWSGI worker 3 (pid: 22107, cores: 8)
spawned uWSGI worker 4 (pid: 22108, cores: 8)
spawned uWSGI worker 5 (pid: 22109, cores: 8)
spawned uWSGI worker 6 (pid: 22110, cores: 8)
spawned uWSGI worker 7 (pid: 22111, cores: 8)
spawned uWSGI worker 8 (pid: 22133, cores: 8)
Mon Dec 17 21:10:04 2018 - received message 0 from emperor
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 2 seconds
worker 2 buried after 2 seconds
worker 3 buried after 2 seconds
worker 4 buried after 2 seconds
worker 5 buried after 2 seconds
worker 6 buried after 2 seconds
worker 7 buried after 2 seconds
worker 8 buried after 2 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 21:10:09 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x145c500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x145c500 pid: 22251 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22251)
spawned uWSGI worker 1 (pid: 22253, cores: 8)
spawned uWSGI worker 2 (pid: 22254, cores: 8)
spawned uWSGI worker 3 (pid: 22255, cores: 8)
spawned uWSGI worker 4 (pid: 22256, cores: 8)
spawned uWSGI worker 5 (pid: 22257, cores: 8)
spawned uWSGI worker 6 (pid: 22258, cores: 8)
spawned uWSGI worker 7 (pid: 22259, cores: 8)
spawned uWSGI worker 8 (pid: 22260, cores: 8)
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Dec 17 21:11:34 2018] ***
compiled with version: 5.4.0 20160609 on 17 December 2018 12:00:26
os: Linux-4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018
nodename: ubuntu-s-1vcpu-1gb-ams3-01
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /
detected binary path: /var/www/html/items-rest/env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 3897
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/www/html/items-rest/socket.sock fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: /var/www/html/items-rest/env
Set PythonHome to /var/www/html/items-rest/env
Python main interpreter initialized at 0x1f2f500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1315008 bytes (1284 KB) for 64 cores
*** Operational MODE: preforking+threaded ***
added /var/www/html/items-rest/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1f2f500 pid: 22327 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22327)
spawned uWSGI worker 1 (pid: 22329, cores: 8)
spawned uWSGI worker 2 (pid: 22330, cores: 8)
spawned uWSGI worker 3 (pid: 22331, cores: 8)
spawned uWSGI worker 4 (pid: 22332, cores: 8)
spawned uWSGI worker 5 (pid: 22333, cores: 8)
spawned uWSGI worker 6 (pid: 22334, cores: 8)
spawned uWSGI worker 7 (pid: 22335, cores: 8)
spawned uWSGI worker 8 (pid: 22357, cores: 8)
[2018-12-17 21:13:09,194] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/var/www/html/items-rest/app.py", line 36, in create_tables
    db.create_all()
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 887, in get_engine
    state = get_state(app)
  File "/var/www/html/items-rest/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_state
    'The sqlalchemy extension was not registered to the current ' \
AssertionError: The sqlalchemy extension was not registered to the current application.  Please make sure to call init_app() first.
[pid: 22357|app: 0|req: 1/1] 81.171.98.46 () {44 vars in 611 bytes} [Mon Dec 17 21:13:09 2018] POST /register => generated 37 bytes in 7 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
announcing my loyalty to the Emperor...
